### PR TITLE
correct bug in lib.sh

### PR DESCRIPTION
**Pull request by enoch85**
Sorry, should have noticed that directly

@rustdesk

### CODE REVIEW

**Comment by rustdesk** [comment]
Can we add github CI for testing these scripts?

**Comment by enoch85** [comment]
> Can we add github CI for testing these scripts?

Yes, sure, something more that is already in place you mean?

**Comment by rustdesk** [comment]
This is a very simple example.
https://github.com/adafruit/ci-arduino/blob/master/.github/workflows/githubci.yml

we can write it like this. But for running CI, we need to make some code change to make it testable. I think it worth.

```
name: Github Arduino Library CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: test install.sh
      run: |
        ./install.sh
       # some script to check if installation successfully.
    - name: test upgrade.sh
      run: |
        ./install.sh
        ./upgrade.sh
```

**Comment by enoch85** [comment]
> This is a very simple example. https://github.com/adafruit/ci-arduino/blob/master/.github/workflows/githubci.yml
> 
> we can write it like this. But for running CI, we need to make some code change to make it testable. I think it worth. e.g. replace `<url>/lib.sh` to local file when testing enabled. How to handle interactive input (https://stackoverflow.com/questions/63252525/how-can-i-automate-a-usually-interactive-build-script-with-github-actions)?
> 
> ```
> name: Github Arduino Library CI
> 
> on: [push]
> 
> jobs:
>   build:
> 
>     runs-on: ubuntu-latest
>     
>     steps:
>     - uses: actions/checkout@v3
>     - name: test install.sh
>       run: |
>         ./install.sh
>        # some script to check if installation successfully.
>     - name: test upgrade.sh
>       run: |
>         ./install.sh
>         ./upgrade.sh
> ```

Please open an issue about it, and I'll have a look when time allows.

**Pull request merged**
