### PR TITLE
Consistency is key!

### PR DESCRIPTION
**Pull request by enoch85**
This PR aims to make everything more consistent, and correct smaller errors/bugs.

### CODE REVIEW

**Comment by enoch85** [comment]
@rustdesk Ready to merge!

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/blob/53a6765771ad3ba95c981ede08d26ddb1bff70ea/install.sh#L406

Looks dangerous, if the user has this file before install RustDesk server.

**Comment by enoch85** [comment]
> https://github.com/rustdesk/rustdesk-server-pro/blob/53a6765771ad3ba95c981ede08d26ddb1bff70ea/install.sh#L406
> 
> Looks dangerous, if the user has this file before install RustDesk server. @dinger1986

I agree, I saw it when I refactored the code, but thought it had a purpose so I left it in there. Vote for removal @rustdesk?

**Comment by enoch85** [comment]
> How do you think about https://github.com/rustdesk/rustdesk-server-pro/blob/main/convertfromos.sh? There may be some inconsistency between install.sh and convertfromos.sh, a lot of duplicate code.

Just had a look, and you're right, we could just to some "migration tasks" and then run the install script directly on top of that. 

Will have a look at that when this is merged.

Just FYI, some original code: https://github.com/rustdesk/rustdesk-server-pro/blob/main/convertfromos.sh#L299-L300

**Comment by dinger1986** [comment]
> https://github.com/rustdesk/rustdesk-server-pro/blob/53a6765771ad3ba95c981ede08d26ddb1bff70ea/install.sh#L406
> 
> Looks dangerous, if the user has this file before install RustDesk server. @dinger1986

yeah could remove it or check if nginx is already installed and then skip removing it would probably have been better actually, I guess in my head I always think itll be on a machine only for RustDesk, if its not most folks will use or should use docker

**Comment by rustdesk** [comment]
> > https://github.com/rustdesk/rustdesk-server-pro/blob/53a6765771ad3ba95c981ede08d26ddb1bff70ea/install.sh#L406
> > 
> > Looks dangerous, if the user has this file before install RustDesk server. @dinger1986
> 
> yeah could remove it or check if nginx is already installed and then skip removing it would probably have been better actually, I guess in my head I always think itll be on a machine only for RustDesk, if its not most folks will use or should use docker

Removing user's file silently is super dangerous, we can not afford this risk. I just removed the lines.

**Pull request merged**
