### PR TITLE
enable shellcheck

### PR DESCRIPTION
**Pull request by enoch85**

### CODE REVIEW

**Comment by rustdesk** [comment]
Should I merge all "enable shellcheck" PRs or only this one?

**Comment by enoch85** [comment]
Sure!

**Comment by rustdesk** [comment]
> Sure!

Merge all PRs?

**Comment by enoch85** [comment]
> > Sure!
> 
> Merge all PRs?

Yes, why not. I could habe done everything in git, but was to lazy to set it up. 

Please merge all PRs into one.

**Pull request merged**
