### PR TITLE
Add uninstaller

### PR DESCRIPTION
**Pull request by enoch85**
This is based on the install script, line by line.

Will maybe make a nicer menu of everything if I have time and motivation.

This PR can be merged as is though.

EDIT: Made a brand new approach to everything. Will update the install script with the new functions when this is merged.

### CODE REVIEW

**Comment by rustdesk** [comment]
How about if the user has installed nginx, curl, ufw etc before running install.sh?

**Comment by enoch85** [comment]
> How about if the user had installed nginx, curl, ufw etc before running install.sh?

I hear you, the script is destructive.

But from my POV, is it better to let the user choose which packages to be uninstalled, or to actually cleanup?

Removing Nginx doesn't remove all configs (/etc/nginx would be intact), and curl and ufw can easily be installed again. 

My view of the regular user is not a power user, rather "I don't know what I'm going so I run a script to make it easier". If you know what you're doing you can remove the things you don't want to be uninstalled by yourself.

But yeah, it could be cho6from a list as well. WDYT?

**Comment by rustdesk** [comment]
> How about if the user had installed nginx, curl, ufw etc before running install.sh?

@dinger1986 do you have any input about this?

**Comment by enoch85** [comment]
Also, I don't expect Rustdesk to be installed on anything else than a dedicated VPS.

**Comment by rustdesk** [comment]
> > How about if the user had installed nginx, curl, ufw etc before running install.sh?
> 
> I hear you, the script is destructive.
> 
> But from my POV, is it better to let the user choose which packages to be uninstalled, or to actually cleanup?
> 
> Removing Nginx doesn't remove all configs (/etc/nginx would be intact), and curl and ufw can easily be installed again.
> 
> My view of the regular user is not a power user, rather "I don't know what I'm going so I run a script to make it easier". If you know what you're doing you can remove the things you don't want to be uninstalled by yourself.
> 
> But yeah, it could be cho6from a list as well. WDYT?

How about not removing nginx etc by default? You can add a command option to let user choose to delete those in an interactive way.

**Comment by enoch85** [comment]
> > > How about if the user had installed nginx, curl, ufw etc before running install.sh?
> > 
> > 
> > I hear you, the script is destructive.
> > But from my POV, is it better to let the user choose which packages to be uninstalled, or to actually cleanup?
> > Removing Nginx doesn't remove all configs (/etc/nginx would be intact), and curl and ufw can easily be installed again.
> > My view of the regular user is not a power user, rather "I don't know what I'm going so I run a script to make it easier". If you know what you're doing you can remove the things you don't want to be uninstalled by yourself.
> > But yeah, it could be cho6from a list as well. WDYT?
> 
> How about not removing nginx etc by default? You can add a command option to let user choose to delete those in an interactive way.

Sure, will have another look at it.

**Comment by enoch85** [comment]
@rustdesk Not tested, but I think this structure is better. What do you think?

**Comment by enoch85** [comment]
@dinger1986 What's your take on this?

**Comment by enoch85** [comment]
@rustdesk Ready to merge.

**Comment by rustdesk** [comment]
👍

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk-server-pro/blob/8bc783c20c0c9ce06eeaca237a9e61f1aa2ddb09/uninstall.sh#L173

https://github.com/rustdesk/rustdesk-server-pro/blob/8bc783c20c0c9ce06eeaca237a9e61f1aa2ddb09/uninstall.sh#L174

Duplicate

**Comment by enoch85** [comment]
> https://github.com/rustdesk/rustdesk-server-pro/blob/8bc783c20c0c9ce06eeaca237a9e61f1aa2ddb09/uninstall.sh#L173
> 
> https://github.com/rustdesk/rustdesk-server-pro/blob/8bc783c20c0c9ce06eeaca237a9e61f1aa2ddb09/uninstall.sh#L174
> 
> Duplicate.
> 
> We may need double check more.

Copy paste mistake.

Will fix and double check the rest.

**Comment by rustdesk** [comment]
Tnanks

**Comment by rustdesk** [comment]
Can we remove `wget/unzip` or make off by default? since I found wget/unzip are installed on most of servers by default.

Also there are UFW/NGINX with upper case, but wget etc are lower case, can we make them consistent? 
image

**Pull request merged**
